docs: Fix a few typos
funkybob/django-nap pull request #81
Opened 2022-08-30 22:01 UTC by timgates42

There are small typos in:
- docs/extras/http.rst
- docs/mapper/fields.rst
- docs/quickstart.rst
- docs/tutorial/mapper.rst
- docs/tutorial/mappers.rst
- docs/tutorial/views.rst
- src/nap/rpc/views.py

Fixes:
- Should read `raisable` rather than `raiseable`.
- Should read `punishable` rather than `pubishable`.
- Should read `passed` rather than `pased`.
- Should read `from` rather than `fron`.
- Should read `composable` rather than `composible`.
- Should read `authenticated` rather than `authentencated`.
- Should read `assigned` rather than `assignd`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

2022-08-30 22:07 UTC, funkybob requested changes
Many thanks for taking the time to spell check my docs!

If you could fix that one wrong word, I'll merge it right away!

2022-08-30 22:07 UTC, funkybob commented on src/nap/rpc/views.py
> -    '''Helper for checking if something is marked as a pubishable method.'''
This should be "publishable"

2022-08-31 10:50 UTC, timgates42 commented on src/nap/rpc/views.py
> -    '''Helper for checking if something is marked as a pubishable method.'''
```suggestion
    '''Helper for checking if something is marked as a publishable method.'''
```

2022-08-31 10:52 UTC, timgates42 commented
> Many thanks for taking the time to spell check my docs!
> 
> If you could fix that one wrong word, I'll merge it right away!

Thanks @funkybob have fixed it up

2022-08-31 23:15 UTC, funkybob approved these changes

2022-08-31 23:15 UTC, merged